### PR TITLE
Sample viewer

### PR DESCRIPTION
**Pull request by pwilliams1**
Main features added:
- Generation of HTML pages into folder specified by user
- Query for Neuroimaging software name and version number
- Query for design matrix location/image
- Query for corrected/uncorrected thresholds (voxel-wise or cluster-wise)
- Query for type of Statistic Image (T, F, Z)
- Some command line support (user can enter NIDM file and HTML output folder)

### CODE REVIEW

**Comment by cmaumet** [comment]
Great! Could you add me (cmaumet) as a collaborator on your forked project so that I can merge the code once reviewed?

**Comment by cmaumet** [comment]
Invitation accepted. Thank you!

**Comment by pwilliams1** [comment]
No problem

**Comment by pwilliams1** [comment]
This PR also fixes #1.

**Comment by cmaumet** [comment]
Hi @pwilliams1: congrats on the quality of your commit messages! 

This PR looks good, I only have a few comments:
- We should really create a `README.md` file including a one line description of the project and an example of usage (cf. https://github.com/incf-nidash/nidmresults-fsl for an example of README.md).
- If the code in the `Initial` folder is no longer used, please delete it (the original code will be kept in git history anyway)

To make these small updates, don't forget to go back to the `sample_viewer` branch before you make any change and then add/commit/push in that branch. The new commits will then appear at the bottom of this page. Let me know if you need any help in the process.

Once these updates are done, I will merge the PR and open new issues for any new comment.

**Comment by pwilliams1** [comment]
I'll add the README and remove the initial folder code. There may be a couple of small changes to viewer.py as I did these before we discussed not editing it while you were reviewing the code, but they should only be small edits (comments, a couple of extra functions etc).

**Comment by cmaumet** [comment]
Commit 8934c17 fixes #4.

**Comment by cmaumet** [comment]
This is good to go.

**Comment by cmaumet** [comment]
@pwilliams1: now that I have merged this PR into `master`, you will need to update your local code as follows:
1. Make sure you don't have any pending updates using:
   
   ```
   git status
   ```
   
   If you have pending updates, git add/ git commit them before proceeding with the following point.
2. Update your master branch (to synchronise with the online `master` branch):
   
   ```
   git checkout master
   git pull upstream master
   ```
3. Delete the `sample_viewer` branch (now merged):
   
   ```
   git branch -d sample_viewer
   ```
   
   /!\ This should go smoothly and delete the branch, if git is complaining and ask you to use the `-D` option (with a capital `D` instead of lower case `d`) option -- do _not_ use it as it means you still have unmerged changes.
4. Go back to the initial branch you were working (replace `MY_ORIGINAL_BRANCH` with your branch name) on and update it with the latest changes:
   
   ```
   git checkout MY_ORIGINAL_BRANCH
   git merge master
   ```

Let me know how it goes!

**Comment by pwilliams1** [comment]
Tried: git pull upstream master

fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

**Comment by cmaumet** [comment]
Sorry `upstream` is only when working with the main nidm repo (which is what we usually do...), because we merged onto your fork, you should do `git pull origin master` rather than `git pull upstream master`. Let me know how it goes!

**Pull request merged**
